// Standard single declaration per line
var a1 = 5;
var a2 = "string";
var a3 = nil;
var a4 = false;
var a5 = true;
var a6;
print("Single dec per line: ");
print("a1=" + tostr(a1) + ", ");
print("a2=" + tostr(a2) + ", ");
print("a3=" + tostr(a3) + ", ");
print("a4=" + tostr(a4) + ", ");
print("a5=" + tostr(a5) + ", ");
printl("a6=" + tostr(a6));
assert(a1 == 5);
assert(a2 == "string");
assert(a3 == nil);
assert(a4 == false);
assert(a5 == true);
assert(a6 == nil);

// Reassign non-fixed variables
a1 = 1;
a2 = 1;
a3 = 1;
a4 = 1;
a5 = 1;
a6 = 1;
print("Single dec per line (reassign): ");
print("a1=" + tostr(a1) + ", ");
print("a2=" + tostr(a2) + ", ");
print("a3=" + tostr(a3) + ", ");
print("a4=" + tostr(a4) + ", ");
print("a5=" + tostr(a5) + ", ");
printl("a6=" + tostr(a6));
assert(a1 == 1);
assert(a2 == 1);
assert(a3 == 1);
assert(a4 == 1);
assert(a5 == 1);
assert(a6 == 1);






// Multiple declarations in a single line
var b1, b2, b3, b4, b5, b6 = 5, "string", nil, false, true;
print("Multiple dec per line: ");
print("b1=" + tostr(b1) + ", ");
print("b2=" + tostr(b2) + ", ");
print("b3=" + tostr(b3) + ", ");
print("b4=" + tostr(b4) + ", ");
print("b5=" + tostr(b5) + ", ");
printl("b6=" + tostr(b6));
assert(b1 == 5);
assert(b2 == "string");
assert(b3 == nil);
assert(b4 == false);
assert(b5 == true);
assert(b6 == nil);

// Multiple assignment of non-fixed variables
b1, b2, b3, b4, b5, b6 = 1, 1, 1, 1, 1, 1;
print("Multiple dec per line (reassign): ");
print("b1=" + tostr(b1) + ", ");
print("b2=" + tostr(b2) + ", ");
print("b3=" + tostr(b3) + ", ");
print("b4=" + tostr(b4) + ", ");
print("b5=" + tostr(b5) + ", ");
printl("b6=" + tostr(b6));
assert(b1 == 1);
assert(b2 == 1);
assert(b3 == 1);
assert(b4 == 1);
assert(b5 == 1);
assert(b6 == 1);




// Standard single declaration of fixed variables per line
fixed var c1 = 5;
fixed var c2 = "string";
fixed var c3 = nil;
fixed var c4 = false;
fixed var c5 = true;
fixed var c6; // should be nil
print("Single fixed dec per line: ");
print("c1=" + tostr(c1) + ", ");
print("c2=" + tostr(c2) + ", ");
print("c3=" + tostr(c3) + ", ");
print("c4=" + tostr(c4) + ", ");
print("c5=" + tostr(c5) + ", ");
printl("c6=" + tostr(c6));
assert(c1 == 5);
assert(c2 == "string");
assert(c3 == nil);
assert(c4 == false);
assert(c5 == true);
assert(c6 == nil);

// Commented lines should fail, assigning to fixed
// variable is a compile-time error.
// c1 = 1;
// c2 = 1;
// c3 = 1;
// c4 = 1;
// c5 = 1;
// c6 = 1;




// Multiple declarations of fixed variables in a single line
fixed var d1, d2, d3, d4, d5, d6 = 5, "string", nil, false, true;
print("Multiple fixed dec per line: ");
print("d1=" + tostr(d1) + ", ");
print("d2=" + tostr(d2) + ", ");
print("d3=" + tostr(d3) + ", ");
print("d4=" + tostr(d4) + ", ");
print("d5=" + tostr(d5) + ", ");
printl("d6=" + tostr(d6));
assert(d1 == 5);
assert(d2 == "string");
assert(d3 == nil);
assert(d4 == false);
assert(d5 == true);
assert(d6 == nil);

// Commented lines should fail, assigning to fixed
// variable is a compile-time error.
// d1 = 1;
// d2 = 1;
// d3 = 1;
// d4 = 1;
// d5 = 1;
// d6 = 1;
