// for loop
for(var x = 0; x < 5; x = x + 1)
    printl("x = " + tostr(x));


// Optimized loop (no conditional)
var x = false;
for(;true;) {
    if(!x) {
        printl("x was false");
        x = true;
        printl("x is now " + tostr(x));
    } else break;
}


// Optimized loop (removed)
for(;false;) {
    printl("This whole block (bytecode) should be deleted.");
    printl("cript can see that conditional is a false constant expression.");
    printl("And it will optimize away the whole for-statement.");
}
