// Global function declaration
fn TestFn(colour, number) {
    printl("My favorite colour is " + colour + " and number " + tostr(number) + ".");
}
TestFn("golden", 1);





// Local function declaration
{
    fn LocalFn(colour, number) {
        printl("My favorite colour is " + colour + " and number " + tostr(number) + ".");
    }
    LocalFn("blue", 7);
}




// Closure
fn CreateClosure() { // FIX OP_GET_UPVALUE
    var x = 24;
    fn Closure() {
        printl("I am " + tostr(x) + " years old.");
        x = x + 1;
        return x;
    }
    return Closure;
}
var closure = CreateClosure();
assert(closure() == 25);
assert(closure() == 26);
assert(closure() == 27);
// and so on...
