// Loop statement
var x = 10;
var lock = true;
loop {
    var a, b, c;
    if(!lock) break;
    printl("Locked!");
    if(x != 8) {
        x = x - 1;
        continue;
    } else lock = false;
    printl("Unlocked!");
}

// Nested loops
var flag1, flag2 = false, false;
loop {
    var a, b, c;
    loop {
        if(flag1) a = 1;
        if(a == nil) {
            flag1 = true;
            continue;
        }
        break;
    }
    if(flag2) b = 1;
    if(b == nil) { 
        flag2 = true;
        continue;
    }
    break;
}

