// While loop

var i = 0;

// Normal loop
while(i < 5) {
    printl("i = " + tostr(i));
    i = i + 1;
}

i = 0;

// Optimized loop (no comparison)
while(true) {
    printl("i = " + tostr(i));
    i = i + 1;
    if(i == 5) break;
}

i = 0;

// Nested loops
while(true) {
    printl("i = " + tostr(i));
    i = i + 1;
    if(i < 5) continue;
    else { 
        assert(i == 5);
        while(true) {
            printl("i = " + tostr(i));
            i = i + 1;
            if(i >= 6) break;
        }
        printl("End loop");
        break; 
    }
}

// Optimized loop (removed)
while(nil) {
    printl("This whole block (bytecode) should be deleted.");
    printl("Skooma can see that conditional is falsey constant expression.");
    printl("And it will optimize away the whole for-statement.");
}
